apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: website-nginx
  namespace: dev
spec:
  ingressClassName: nginx
  rules:
    - host: dev.matthieuclement.com
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: website-service
              port:
                number: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: website-service
  namespace: dev
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: website

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  namespace: dev
spec:
  selector:
    matchLabels:
      app: website
  replicas: 2
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: website
        image: frontend:dev
        #image: hashicorp/http-echo
          #args:
          #- "-text=Hello Kubernetes!"
          #- "-listen=:80"
        ports:
        - containerPort: 8080