apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: website-backend-nginx
  namespace: dev
spec:
  ingressClassName: nginx
  rules:
    - host: dev.matthieuclement.com
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: website-backend-service
              port:
                number: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: website-backend-service
  namespace: dev
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: website-backend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-backend
  namespace: dev
spec:
  selector:
    matchLabels:
      app: website-backend
  replicas: 2
  template:
    metadata:
      labels:
        app: website-backend
    spec:
      volumes:
      - name: data
        hostPath:
          path: ~/data
      containers:
      - name: website-backend
        image: website-backend:dev
        volumeMounts:
          - name: data
          - mountPath: /data
          - readonly: true
        env:
        - name: RESUME_FILEPATH
          value: /data/resume.pdf
        - name: SERVER_PORT
          value: 8080
        ports:
        - containerPort: 8080