apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: website-backend-nginx
spec:
  ingressClassName: nginx
  rules:
    - host: www.matthieuclement.com
      http:
        paths:
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: website-backend-service
              port:
                number: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: website-backend-service
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: website-backend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-backend
spec:
  selector:
    matchLabels:
      app: website-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: website-backend
    spec:
      volumes:
      - name: data
        hostPath:
          path: /home/debian/data
      containers:
      - name: website-backend
        image: website-backend:main
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8080
        volumeMounts:
        - name: data
          mountPath: /data
        env:
        - name: PREFIX_PATH
          value: /api
        - name: RESUME_FILEPATH
          value: /data/CV_Matthieu_CLEMENT_English.pdf
        - name: SERVER_PORT
          value: "8080"
        ports:
        - containerPort: 8080