spring.application.name=backend
server.port=${SERVER_PORT}

application.version=@project.version@

file.resume-filepath=${RESUME_FILEPATH}

server.servlet.context-path=${PREFIX_PATH}

spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
contact.email=${MAIL_USERNAME}
contact.url=${FRONTEND_URL}

settings.cors_origins=${FRONTEND_URL}

friendlycaptcha.api-key=${FRIENDLY_CAPTCHA_API_KEY}
friendlycaptcha.site-key=${FRIENDLY_CAPTCHA_SITE_KEY}
