spring.application.name=backend
server.port=${SERVER_PORT}

application.version=@project.version@

file.resume-filepath=${RESUME_FILEPATH}

server.servlet.context-path=${PREFIX_PATH}

spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.starttls.required=false
contact.email=${MAIL_USERNAME}
contact.prefix=[${FRONTEND_URL}] :

settings.cors_origins=${FRONTEND_URL}

friendlycaptcha.api-key=${FRIENDLY_CAPTCHA_API_KEY}
friendlycaptcha.site-key=${FRIENDLY_CAPTCHA_SITE_KEY}
