spring.application.name=backend
server.port=8081

application.version=@project.version@

file.resume-filepath=./data/resume.pdf

server.servlet.context-path=/api


spring.mail.host=localhost
spring.mail.port=1025
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.starttls.required=false
contact.email=contact@example.com
contact.url=example.com

settings.cors_origins=http://localhost:8080

friendlycaptcha.api-key=${FRIENDLY_CAPTCHA_API_KEY}
friendlycaptcha.site-key=${FRIENDLY_CAPTCHA_SITE_KEY}
