spring.application.name=backend
server.port=8080

application.version=@project.version@

file.resume-filepath=./data/resume.pdf

server.servlet.context-path=/api


spring.mail.host=localhost
spring.mail.port=1025
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.starttls.required=false
contact.email=contact@example.com
contact.prefix=[example.com] :

settings.cors_origins=http://localhost:5173

# Replace with API key -> https://app.friendlycaptcha.eu/
friendlycaptcha.api-key=XXXXXX
# Replace with site key -> https://app.friendlycaptcha.eu/
friendlycaptcha.site-key=XXXXXX
