name: Test build

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]


jobs:

  build-node:

    runs-on: ubuntu-latest

    # Custom add for ./frontend
    defaults:
      run:
        working-directory: 'frontend'

    strategy:
      matrix:
        node-version: [20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - run: npm ci
    - run: npm run build --if-present
    #- run: npm test

  build-docker-image:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --tag matthiosso/website:$(date +%s)
