name: Test build

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]


jobs:

  build-node:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: 'frontend'

    strategy:
      matrix:
        node-version: [20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - run: npm ci
    - run: npm run build --if-present
    #- run: npm test

  build-maven:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: 'backend'

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 24 for x64
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'temurin'
    - name: Run the Maven verify phase
      run: mvn --batch-mode --update-snapshots verify
  
  build-docker-image:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Frontend Docker image
      run: cd frontend && docker build . --tag matthiosso/website-frontend:$(date +%s)

    - uses: actions/checkout@v4
    - name: Build the Backend Docker image
      run: cd backend && docker build . --tag matthiosso/website-backend:$(date +%s)
